service: serverless-vaccines-api

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline

functions:
  testEndpoint:
    handler: functions/handler.testEndpoint
    events:
      - http:
          path: test-endpoint
          method: get
          cors: true

custom:
  serverless-offline:
    httpPort: 3001
