service: serverless-vaccines-api

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline

functions:
  testEndpoint:
    handler: functions/handler.testEndpoint
    events:
      - http:
          path: test-endpoint
          method: get
          cors: true
  getAllTimeData:
    handler: functions/handler.getAllTimeData
    events:
      - http:
          path: all-time-data
          method: get
          cors: true
  getPerDayData:
    handler: functions/handler.getPerDayData
    events:
      - http:
          path: /per-day-data/{date}
          method: get
          cors: true
  startMySQLConnection:
    handler: functions/mysql/connection.startConnection
    events:
      - http:
          path: start-mysql-connection
          method: get
          cors: true
  endMySQLConnection:
    handler: functions/mysql/connection.endConnection
    events:
      - http:
          path: end-mysql-connection
          method: get
          cors: true

custom:
  serverless-offline:
    httpPort: 3001
